# Generated by Django 3.1.3 on 2020-11-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapiapp', '0002_wallettransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='transaction_type',
            field=models.CharField(max_length=10),
        ),
    ]
